//! Preprocessed-trace generation for the M10.1c composite AIR.
//!
//! **Pearl ISC.** This file is derived from Pearl source code
//! (Copyright (c) 2025-2026 Pearl Research Labs; 2015-2016 The Decred
//! developers); see `crates/ai-pow-zk/LICENSE-PEARL` for the full
//! permission notice.
//!
//! Port of `Pearl zk-pow pearl_preprocess.rs`,
//! simplified to the minimum we need for the chip wiring landed in
//! Phases 2–5. Pearl's full preprocessor is tied to a multi-
//! thousand-line program-compilation pipeline (`pearl_program.rs`)
//! that emits row-by-row chip-instruction sequences; that's tracked
//! as Phase 12+ work. This module ships the *type-level* row schedule
//! plus the per-row preprocessed-column generator the existing chips
//! consume.
//!
//! ## Preprocessed columns
//!
//! Per `composite_layout.rs` and Pearl, the preprocessed-trace slice
//! holds:
//!
//!   * `CONTROL_PREP`        — 21 selector bits + 26-bit `MAT_ID`,
//!     bit-packed into one Goldilocks element.
//!   * `NOISE_PACKED_PREP`   — packed noise (polyval base 129).
//!   * `CV_OR_TWEAK_PREP`    — either a CV-routing row index or a
//!     BLAKE3 compression tweak.
//!   * `AB_ID_PREP`          — packed first `(A_ID, B_ID)` pair.
//!   * `A_ID` / `B_ID`       — exact A/B position IDs for the
//!     matmul row's four 8-byte sub-slice reads.
//!   * `STARK_ROW_IDX`       — monotonic row counter (filled by the
//!     stark_row chip's `fill_row`; included here for completeness).
//!
//! Each per-row preprocessed value is a pure function of the row's
//! position in the program. The trace generator (Phase 13) builds
//! the per-row "instruction" descriptor; this module turns it into
//! the column values.
//!
//! ## Property enforced
//!
//! The preprocessed-trace generator's "property" is just consistency
//! between the preprocessed values and the main-trace columns the
//! chips constrain. The control chip (Phase 5) already enforces
//! `CONTROL_PREP = polyval(selectors + MAT_ID, 2)`; the preprocessor
//! must emit the same packed value. Tests below confirm round-trip
//! coherence: a preprocessed slice generated by this module can be
//! used as-is by the existing chip evaluators.

use crate::chips::control::{ControlChip, NUM_SELECTORS};
use crate::composite_layout::{
    AB_ID_LIMBS_START, AB_ID_PREP, A_ID, A_ID_LEN, BITS_PER_LIMB, B_ID, B_ID_LEN, CONTROL_PREP,
    CV_OR_TWEAK_PREP, NOISE_PACKED_PREP, RB_CONTROL_PREP, STARK_ROW_IDX, SX_CONTROL_PREP,
};
use crate::Val;

/// Per-row instruction descriptor. Subsequent phases (matmul,
/// jackpot, BLAKE3) extend this with their per-chip control bits
/// + per-row data. For now we expose just the fields the existing
/// chips need.
#[derive(Debug, Clone, Copy, Default)]
pub struct RowDescriptor {
    /// 21 selector bits in the canonical Pearl order (see
    /// `chips::control::SELECTOR_COLS`).
    pub selectors: [bool; NUM_SELECTORS],
    /// Matrix-tile index used by the matmul chip's RAM lookup
    /// (Phase 9). For non-matmul rows, set to 0.
    pub mat_id: u32,
    /// Preprocessed noise word — `NOISE_PACKED_PREP[0]` (sub-slice
    /// 0). For non-matrix rows, 0.
    pub noise_packed: i64,
    /// The 7 *additional* co-located
    /// leaf-row noise sub-slice pins `NOISE_PACKED_PREP[1..8]`
    /// (sub-slice `s` ⇒ `noise_packed_hi[s-1]`). 0 on every
    /// non-co-located row (zero-blast / pre-co-location byte-identical).
    /// The canonical program reconstructs these params-pure
    /// (`polyval(noise_ref(s_a/s_b at the leaf (i,l)), 129)`).
    pub noise_packed_hi: [i64; 7],
    /// CV-routing index or BLAKE3 tweak (Phase 7+). For non-BLAKE3
    /// rows, set to 0.
    pub cv_or_tweak: u64,
    /// Packed first `(A_ID, B_ID)` pair for matmul tile loads. For
    /// non-matmul rows, set to 0.
    pub ab_id: u64,
    /// Exact position IDs for the four A-side 8-byte sub-slices
    /// consumed by this matmul row.
    pub a_ids: [u64; A_ID_LEN],
    /// Exact position IDs for the four B-side 8-byte sub-slices
    /// consumed by this matmul row.
    pub b_ids: [u64; B_ID_LEN],
    /// 1 on a FoldChip fold row (pinned into
    /// `CONTROL_PREP` at bit 2^47). For non-fold rows, `false`.
    pub is_fold: bool,
    /// Fold slot index (`stripe % 16`, pinned into
    /// `CONTROL_PREP` at bit 2^48). For non-fold rows, `0`.
    pub fold_slot: u8,
    /// Fold stripe index (`0..STRIPE_MAX`,
    /// pinned into `CONTROL_PREP` at bit 2^52 — the keystone's
    /// SX_XR lane selector). For non-fold rows, `0`.
    pub fold_stripe: u8,
    /// C3 message word-pair index `p`
    /// (`0..8`, pinned into `CONTROL_PREP` at bit 2^58 — the
    /// generalized-C3 leaf word-pair selector). For
    /// non-C3-leaf rows, `0`.
    pub msg_pair: u8,
    /// 1 on the first StripeXor sweep row of a stripe
    /// segment `g > 0` (pinned into `CONTROL_PREP` at bit 2^61 — the
    /// verifier-fixed StripeXor register reset). For the single-segment
    /// path and every other row, `false`.
    pub seg_reset: bool,
    /// Compact verifier-pinned StripeXor schedule control.
    pub sx_control: u64,
    /// Compact verifier-pinned R-b TileAccum/TileReduce schedule control.
    pub rb_control: u64,
}

impl RowDescriptor {
    /// All-zero descriptor — a padding row.
    pub const fn padding() -> Self {
        Self {
            selectors: [false; NUM_SELECTORS],
            mat_id: 0,
            noise_packed: 0,
            noise_packed_hi: [0; 7],
            cv_or_tweak: 0,
            ab_id: 0,
            a_ids: [0; A_ID_LEN],
            b_ids: [0; B_ID_LEN],
            is_fold: false,
            fold_slot: 0,
            fold_stripe: 0,
            msg_pair: 0,
            seg_reset: false,
            sx_control: 0,
            rb_control: 0,
        }
    }
}

pub fn pack_ab_id(a_id: u64, b_id: u64) -> u64 {
    assert!(a_id < (1u64 << (2 * BITS_PER_LIMB)));
    assert!(b_id < (1u64 << (2 * BITS_PER_LIMB)));
    a_id | (b_id << (2 * BITS_PER_LIMB))
}

/// Generate preprocessed-column values for one row. Writes
/// `CONTROL_PREP`, `NOISE_PACKED_PREP`, `CV_OR_TWEAK_PREP`,
/// `AB_ID_PREP`, `A_ID`, `B_ID`, `STARK_ROW_IDX`, and the compact
/// verifier-pinned schedule words directly into `row`.
///
/// Caller is responsible for providing the rest of the row data
/// (chip-internal columns are filled by each chip's `fill_row`).
pub fn fill_preprocessed_row(row_idx: usize, desc: &RowDescriptor, row: &mut [Val]) {
    use p3_field::integers::QuotientMap;

    // CONTROL_PREP: pack selectors + mat_id +
    // the FoldChip schedule (is_fold, slot, stripe).
    let control_prep = ControlChip::pack_control_prep_full(
        &desc.selectors, desc.mat_id, desc.is_fold, desc.fold_slot, desc.fold_stripe,
        desc.msg_pair, desc.seg_reset,
    );
    row[CONTROL_PREP] = <Val as QuotientMap<u64>>::from_int(control_prep);

    // NOISE_PACKED_PREP[0..8], CV_OR_TWEAK_PREP, AB_ID_PREP: direct.
    row[NOISE_PACKED_PREP] = <Val as QuotientMap<i64>>::from_int(desc.noise_packed);
    for s in 0..7 {
        row[NOISE_PACKED_PREP + 1 + s] =
            <Val as QuotientMap<i64>>::from_int(desc.noise_packed_hi[s]);
    }
    row[CV_OR_TWEAK_PREP] = <Val as QuotientMap<u64>>::from_int(desc.cv_or_tweak);
    row[AB_ID_PREP] = <Val as QuotientMap<u64>>::from_int(desc.ab_id);
    for i in 0..A_ID_LEN {
        row[A_ID + i] = <Val as QuotientMap<u64>>::from_int(desc.a_ids[i]);
    }
    for i in 0..B_ID_LEN {
        row[B_ID + i] = <Val as QuotientMap<u64>>::from_int(desc.b_ids[i]);
    }
    let mask = (1u64 << BITS_PER_LIMB) - 1;
    row[AB_ID_LIMBS_START] = <Val as QuotientMap<u64>>::from_int(desc.ab_id & mask);
    row[AB_ID_LIMBS_START + 1] =
        <Val as QuotientMap<u64>>::from_int((desc.ab_id >> BITS_PER_LIMB) & mask);
    row[AB_ID_LIMBS_START + 2] =
        <Val as QuotientMap<u64>>::from_int((desc.ab_id >> (2 * BITS_PER_LIMB)) & mask);
    row[AB_ID_LIMBS_START + 3] =
        <Val as QuotientMap<u64>>::from_int((desc.ab_id >> (3 * BITS_PER_LIMB)) & mask);

    // STARK_ROW_IDX: monotonic row counter.
    row[STARK_ROW_IDX] = <Val as QuotientMap<u64>>::from_int(row_idx as u64);
    row[SX_CONTROL_PREP] = <Val as QuotientMap<u64>>::from_int(desc.sx_control);
    row[RB_CONTROL_PREP] = <Val as QuotientMap<u64>>::from_int(desc.rb_control);
}

/// Convenience: build a full per-row preprocessed table for a
/// program of length `program.len()`, padded to `total_rows`. Pads
/// with [`RowDescriptor::padding`] entries.
pub fn build_preprocessed_columns(program: &[RowDescriptor], total_rows: usize) -> Vec<[Val; 22]> {
    use p3_field::integers::QuotientMap;
    assert!(total_rows >= program.len(), "total_rows < program length");
    let mut out = Vec::with_capacity(total_rows);
    for row_idx in 0..total_rows {
        let desc = if row_idx < program.len() {
            program[row_idx]
        } else {
            RowDescriptor::padding()
        };
        let control_prep = ControlChip::pack_control_prep_full(
            &desc.selectors, desc.mat_id, desc.is_fold, desc.fold_slot, desc.fold_stripe,
            desc.msg_pair, desc.seg_reset,
        );
        // PROGRAM_COLS order = [CONTROL_PREP,
        // NOISE_PACKED_PREP+0..8, CV_OR_TWEAK_PREP, AB_ID_PREP,
        // A_ID[0..4], B_ID[0..4], STARK_ROW_IDX,
        // SX_CONTROL_PREP, RB_CONTROL_PREP].
        let hi = desc.noise_packed_hi;
        let q = |v: i64| <Val as QuotientMap<i64>>::from_int(v);
        out.push([
            <Val as QuotientMap<u64>>::from_int(control_prep),
            q(desc.noise_packed),
            q(hi[0]),
            q(hi[1]),
            q(hi[2]),
            q(hi[3]),
            q(hi[4]),
            q(hi[5]),
            q(hi[6]),
            <Val as QuotientMap<u64>>::from_int(desc.cv_or_tweak),
            <Val as QuotientMap<u64>>::from_int(desc.ab_id),
            <Val as QuotientMap<u64>>::from_int(desc.a_ids[0]),
            <Val as QuotientMap<u64>>::from_int(desc.a_ids[1]),
            <Val as QuotientMap<u64>>::from_int(desc.a_ids[2]),
            <Val as QuotientMap<u64>>::from_int(desc.a_ids[3]),
            <Val as QuotientMap<u64>>::from_int(desc.b_ids[0]),
            <Val as QuotientMap<u64>>::from_int(desc.b_ids[1]),
            <Val as QuotientMap<u64>>::from_int(desc.b_ids[2]),
            <Val as QuotientMap<u64>>::from_int(desc.b_ids[3]),
            <Val as QuotientMap<u64>>::from_int(row_idx as u64),
            <Val as QuotientMap<u64>>::from_int(desc.sx_control),
            <Val as QuotientMap<u64>>::from_int(desc.rb_control),
        ]);
    }
    out
}

#[cfg(test)]
mod tests {
    use p3_field::PrimeField64;

    use super::*;
    use crate::chips::control::NUM_SELECTORS;
    use crate::composite_layout::{
        AB_ID_PREP, BITS_PER_LIMB, CONTROL_PREP, CV_OR_TWEAK_PREP, NOISE_PACKED_PREP,
        RB_CONTROL_PREP, STARK_ROW_IDX, SX_CONTROL_PREP, TOTAL_TRACE_WIDTH,
    };

    #[test]
    fn padding_descriptor_is_all_zero() {
        let p = RowDescriptor::padding();
        assert!(p.selectors.iter().all(|&b| !b));
        assert_eq!(p.mat_id, 0);
        assert_eq!(p.noise_packed, 0);
        assert_eq!(p.cv_or_tweak, 0);
        assert_eq!(p.ab_id, 0);
    }

    #[test]
    fn fill_preprocessed_row_writes_pinned_columns() {
        let mut row = vec![Val::default(); TOTAL_TRACE_WIDTH];
        let mut selectors = [false; NUM_SELECTORS];
        selectors[0] = true; // IS_RESET_CUMSUM
        selectors[7] = true; // IS_CV_IN
        let desc = RowDescriptor {
            selectors,
            mat_id: 42,
            noise_packed: 1234,
            cv_or_tweak: 99,
            ab_id: 0xDEAD,
            sx_control: 0x55,
            rb_control: 0x155,
            ..RowDescriptor::padding()
        };
        fill_preprocessed_row(17, &desc, &mut row);

        // CONTROL_PREP: packed (1 << 0) | (1 << 7) | (42 << 21).
        let expected_control_prep = 1u64 | (1 << 7) | (42u64 << NUM_SELECTORS);
        assert_eq!(row[CONTROL_PREP].as_canonical_u64(), expected_control_prep);

        // NOISE_PACKED_PREP / CV_OR_TWEAK_PREP / AB_ID_PREP direct.
        assert_eq!(row[NOISE_PACKED_PREP].as_canonical_u64(), 1234);
        assert_eq!(row[CV_OR_TWEAK_PREP].as_canonical_u64(), 99);
        assert_eq!(row[AB_ID_PREP].as_canonical_u64(), 0xDEAD);

        // STARK_ROW_IDX = row index.
        assert_eq!(row[STARK_ROW_IDX].as_canonical_u64(), 17);
        assert_eq!(row[SX_CONTROL_PREP].as_canonical_u64(), 0x55);
        assert_eq!(row[RB_CONTROL_PREP].as_canonical_u64(), 0x155);
    }

    /// Round-trip: pack control with ControlChip::pack_control_prep,
    /// then fill via fill_preprocessed_row, then unpack. Must match.
    #[test]
    fn fill_preprocessed_row_matches_control_chip_pack() {
        let mut row = vec![Val::default(); TOTAL_TRACE_WIDTH];
        let mut selectors = [false; NUM_SELECTORS];
        for i in (0..NUM_SELECTORS).step_by(3) {
            selectors[i] = true;
        }
        let mat_id = 0xABC;
        let desc = RowDescriptor {
            selectors,
            mat_id,
            ..RowDescriptor::padding()
        };
        fill_preprocessed_row(0, &desc, &mut row);
        let expected = ControlChip::pack_control_prep(&selectors, mat_id);
        assert_eq!(row[CONTROL_PREP].as_canonical_u64(), expected);
    }

    /// `build_preprocessed_columns` produces the pinned per-row tuple
    /// matching `fill_preprocessed_row`.
    #[test]
    fn build_preprocessed_columns_matches_fill_row() {
        let program = vec![
            RowDescriptor {
                selectors: [true; NUM_SELECTORS],
                mat_id: 11,
                noise_packed: -77,
                cv_or_tweak: 4,
                ab_id: 5,
                ..RowDescriptor::padding()
            },
            RowDescriptor {
                selectors: [false; NUM_SELECTORS],
                mat_id: 0,
                noise_packed: 0,
                cv_or_tweak: 0,
                ab_id: 0,
                ..RowDescriptor::padding()
            },
        ];
        let total_rows = 4;
        let out = build_preprocessed_columns(&program, total_rows);
        assert_eq!(out.len(), total_rows);

        // Row 0: matches the first program entry.
        let mut row0 = vec![Val::default(); TOTAL_TRACE_WIDTH];
        fill_preprocessed_row(0, &program[0], &mut row0);
        // PROGRAM_COLS is 22 — [0]=CONTROL_PREP,
        // [1]=NOISE_PACKED_PREP cell 0, [2..9]=the 7 added
        // sub-slice pins (0 until co-location), [9]=CV_OR_TWEAK_PREP,
        // [10]=AB_ID_PREP, [11..15]=A_ID[0..4),
        // [15..19]=B_ID[0..4), [19]=STARK_ROW_IDX,
        // [20]=SX_CONTROL_PREP, [21]=RB_CONTROL_PREP.
        assert_eq!(out[0][0], row0[CONTROL_PREP]);
        assert_eq!(out[0][1], row0[NOISE_PACKED_PREP]);
        for k in 2..9 {
            assert_eq!(out[0][k].as_canonical_u64(), 0);
        }
        assert_eq!(out[0][9], row0[CV_OR_TWEAK_PREP]);
        assert_eq!(out[0][10], row0[AB_ID_PREP]);
        for k in 0..crate::composite_layout::A_ID_LEN {
            assert_eq!(out[0][11 + k], row0[A_ID + k]);
        }
        for k in 0..crate::composite_layout::B_ID_LEN {
            assert_eq!(out[0][15 + k], row0[B_ID + k]);
        }
        assert_eq!(out[0][19], row0[STARK_ROW_IDX]);
        assert_eq!(out[0][20], row0[SX_CONTROL_PREP]);
        assert_eq!(out[0][21], row0[RB_CONTROL_PREP]);

        // Row 1: matches the second program entry (all zero).
        assert_eq!(out[1][0].as_canonical_u64(), 0);
        assert_eq!(out[1][19].as_canonical_u64(), 1);

        // Row 2 & 3: padding (all zero except STARK_ROW_IDX).
        for r in 2..total_rows {
            assert_eq!(out[r][0].as_canonical_u64(), 0);
            assert_eq!(out[r][1].as_canonical_u64(), 0);
            assert_eq!(out[r][9].as_canonical_u64(), 0);
            assert_eq!(out[r][10].as_canonical_u64(), 0);
            assert_eq!(out[r][19].as_canonical_u64(), r as u64);
            assert_eq!(out[r][20].as_canonical_u64(), 0);
            assert_eq!(out[r][21].as_canonical_u64(), 0);
        }
    }

    /// STARK_ROW_IDX increments monotonically across the table.
    #[test]
    fn stark_row_idx_is_monotonic() {
        let program = vec![RowDescriptor::padding(); 4];
        let out = build_preprocessed_columns(&program, 8);
        for r in 0..8 {
            // STARK_ROW_IDX remains at PROGRAM_COL index 19.
            assert_eq!(out[r][19].as_canonical_u64(), r as u64);
        }
    }

    /// MAT_ID limb decomposition stored implicitly inside
    /// `CONTROL_PREP` matches the control chip's expected layout
    /// (limb0 = lower 13 bits, limb1 = next 13 bits).
    #[test]
    fn mat_id_limb_decomposition_matches() {
        let mat_id: u32 = (0b101 << BITS_PER_LIMB) | 0b110_0110_1010_11; // 13-bit limb0 + 3-bit limb1
        let selectors = [false; NUM_SELECTORS];
        let packed = ControlChip::pack_control_prep(&selectors, mat_id);
        // Recover MAT_ID from the packed value: bits 21..47.
        let recovered_mat_id =
            ((packed >> NUM_SELECTORS) & ((1u64 << (2 * BITS_PER_LIMB)) - 1)) as u32;
        assert_eq!(recovered_mat_id, mat_id);
    }
}
