/=  dcon  /apps/dumbnet/lib/consensus
/=  dmin  /apps/dumbnet/lib/miner
/=  *  /apps/dumbnet/lib/types
/=  *  /common/zeke
/=  *  /common/h-zoon
/=  tx-engine  /common/tx-engine
/=  *  /common/test
/=  helpers  /tests/dumb/helpers
::
|_  constants=_bc-v0-phase:helpers
+*  t  ~(. tx-engine constants)
    h  ~(. helpers constants)
::  +der: pre-activation derived-state (read-only extra arg for consensus/miner doors)
++  der  ^-  derived-state  *derived-state
++  test-add-genesis-page
  =/  con=consensus-state  initial-consensus-state:h
  ::
  =/  balance-expect  *(h-mip block-id:t nname:t nnote:t)
  =/  txs-expect  *(h-mip block-id:t tx-id:t tx:t)
  =/  blocks-expect
    %+  ~(put h-by *(h-map block-id:t local-page:t))
    default-genesis-id:h  (to-local-page:page:t default-genesis-page:h)
  =/  heaviest-expect  (some default-genesis-id:h)
  =/  min-timestamps-expect
    %+  ~(put h-by *(h-map block-id:t @))
    default-genesis-id:h  (time-in-secs:page:t *@da)
  =/  epoch-start-expect
    %+  ~(put h-by *(h-map block-id:t block-id:t))
    default-genesis-id:h  default-genesis-id:h
  =/  target-expect
    %+  ~(put h-by *(h-map block-id:t bignum:bignum))
    default-genesis-id:h  genesis-target:t
  =/  btc-data-expect  ``*btc-hash:t
  =/  genesis-seal-expect  `[0 (from-b58:hash:t default-genesis-seal:h)]
  =/  con-expect=consensus-state
    %*  .  *consensus-state
      balance  balance-expect
      txs      txs-expect
      blocks   blocks-expect
      heaviest-block  heaviest-expect
      min-timestamps  min-timestamps-expect
      epoch-start  epoch-start-expect
      targets  target-expect
      btc-data  btc-data-expect
      genesis-seal  genesis-seal-expect
    ==
  ::
  %+  expect-eq  !>(con-expect)
  !>(con)
::
++  test-spend-coinbase-before-timelock
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  tac=tx-acc:t  (new:tx-acc:t (~(get h-by balance.con) ~(digest get:page:t new-page)) 2)
  =/  res=(reason tx-acc:t)  (process:tx-acc:t tac raw-tx.tx)
  %+  expect-eq  !>(%.n)
  !>(-.res)
::
++  test-exceeds-max-block-size-one
  =.  constants  bc-max-block-one:helpers
  =/  con=consensus-state  initial-consensus-state:h
  =/  last-page=page:t
    (to-page:local-page:t (~(got h-by blocks.con) (need heaviest-block.con)))
  =/  new-page  (make-empty-page:h last-page)
  %+  expect-eq
    !>([%.n %block-too-large])
  !>((~(validate-page-with-txs dcon con der constants) new-page))
::
++  test-exceeds-medium-block-size
  =.  constants  bc-max-block-size-medium-v0:helpers
  =/  con=consensus-state  initial-consensus-state:h
  =/  min=mining-state  initial-mining-state:h
  =/  curr-page=page:t  default-genesis-page:h
  =|  [i=@ txs=(list raw-tx:t)]
  ::
  =/  [con=consensus-state min=mining-state txs=(list raw-tx:t)]
    |-
    ?:  =(50 i)
      [con min txs]
    =/  new-page  (make-empty-page:h curr-page)
    =/  r=(reason tx-acc:t)  (~(validate-page-with-txs dcon con der constants) new-page)
    ?.  ?=(%.y -.r)
      ~&  failed-reason++.r  !!
    =/  acc=tx-acc:t  +.r
    =.  con  (~(accept-page dcon con der constants) new-page acc *@da)
    =.  con  (~(update-heaviest dcon con der constants) new-page)
    =.  con  (~(garbage-collect dcon con der constants) default-retain:h)
    =.  min  (~(heard-new-block dmin min der constants) con *@da)
    =/  =coinbase:t  (new:v0:coinbase:t new-page p:default-keys-1:h)
    ?>  ?=(^ -.coinbase)
    =/  raw  (simple-from-note:new:raw-tx:v0:t p:default-keys-2:h coinbase s:default-keys-1:h)
    $(i +(i), curr-page new-page, txs [raw txs], con con, min min)
  =/  attempt-add=(unit mining-state)
    %-  mole
    |.
    %+  roll
      txs
    |=  [=raw-tx:t min=_min]
    =/  new-min  (~(heard-new-tx dmin min der constants) raw-tx)
    ::  We are asserting that the mining state has changed here
    ::  If it hasn't changed, that means that adding the raw-tx
    ::  causes the block size to exceed the limit.
    ?<  =(new-min min)
    new-min
  ::
  ::  attempting to add the transactions should fail
  ::  because the block size exceeds the limit
  ?>  ?=(~ attempt-add)
  ~
::
++  test-raw-tx-not-based
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  ::
  ::  create raw-tx to twiddle
  =/  raw1=raw-tx:t
    (simple-from-note:new:raw-tx:v0:t p:default-keys-2:h coin1 s:default-keys-1:h)
  ::
  ::  twiddle id to be out of field, this would not be a valid raw-tx
  ::  generated by new:v0:raw-tx. we are checking if someone is maliciously
  ::  submitting txs.
  ?>  ?=(^ -.raw1)
  =.  id.raw1
    [p (dec p) (dec p) (dec p) (dec p)]
  ::
  ::  create second raw-tx to twiddle
  =/  raw2=raw-tx:t
    (simple-from-note:new:raw-tx:v0:t p:default-keys-2:h coin1 s:default-keys-1:h)
  ::
  ::  twiddle coinbase lock to be out of field, we want run a based check
  ::  that is deep inside of of the tx structure
  ?>  ?=(^ -.raw2)
  =/  ips=inputs:t
    =/  inps  ~(tap z-by inputs.raw2)
    ?>  =(1 (lent inps))
    =/  [=nname:t =$>(%0 input:t)]  =-  [-< [%0 ->]]  (snag 0 inps)
    =/  seds  ~(tap z-in seeds.spend.input)
    ?>  =(1 (lent seds))
    =/  sed  (snag 0 seds)
    =.  timelock-intent.sed  `[[`0 ``@ud`p] [~ ~]]
    %+  ~(put z-by *inputs:t)
      nname
    input(seeds.spend (~(put z-in *(z-set seed:t)) sed))
  =.  inputs.raw2  (into:v0:inputs:t ips)
  %+  weld
    %+  expect-eq
      !>(%.n)
    !>((based:raw-tx:t raw1))
  %+  expect-eq
    !>(%.n)
  !>((based:raw-tx:t raw2))
::
++  test-spend-coinbase-after-timelock
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  ::
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 102)
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)
    (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t make-default-coinbase:v0:h))
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  ?>  ?=(^ -.new-note)
  =/  new-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note))
  %+  expect-eq
    !>  [%.n %.y]
  !>  [old-in-balance new-in-balance]
::
++  test-double-spend-coinbase-after-timelock
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  =/  new-page=page:t  (make-empty-page:h par)
  ::
  =/  tx1=tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 102)
  =/  tx2=tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-3:h) 102)
  ?>  ?=(^ -.raw-tx.tx1)
  ?>  ?=(^ -.raw-tx.tx2)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(gas z-in *(z-set tx-id:t)) ~[id.raw-tx.tx1 id.raw-tx.tx2])
      ==
    %=  new-page
      tx-ids  (~(gas z-in *(z-set tx-id:t)) ~[id.raw-tx.tx1 id.raw-tx.tx2])
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx1)
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx2)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  -:(~(validate-page-with-txs dcon con der constants) new-page)
  %+  expect-eq
    !>(%.n)
  !>(tac)
::
::  assets spent must be exactly equal to assets in the note. if you
::  try to construct a raw-tx where this is not the case, it should fail.
++  test-single-utxo-invalid-spend-construction-fail
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  ::
  ::  Overspend from note
  =/  seed1=seed:t
    %*  .  *seed:t
      gift  +(assets.coinbase)
      recipient  p:default-keys-2:h
      parent-hash  (hash:nnote:t coinbase)
    ==
  ::  Underspend from note
  =/  seed2=seed:t
    seed1(gift (dec assets.coinbase))
  =/  inp1=$>(%0 input:t)
    ($:new:v0:input:t coinbase (~(put z-in *seeds:t) seed1) 0 s:default-keys-1:h)
  =/  inp2=$>(%0 input:t)
    ($:new:v0:input:t coinbase (~(put z-in *seeds:t) seed2) 0 s:default-keys-1:h)
  =/  ips1=inputs:t
    (new:v0:inputs:t inp1)
  =/  ips2=inputs:t
    (new:v0:inputs:t inp2)
  =/  raw1  (mole |.((from-inputs:v0:raw-tx:t ips1)))
  =/  raw2  (mole |.((from-inputs:v0:raw-tx:t ips2)))
  %+  expect-eq
    !>([~ ~])  :: should fail to build invalid transactions
  !>([raw1 raw2])
::
++  test-two-to-one-utxo-spend
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =^  page2=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =/  coin2=coinbase:t  (new:v0:coinbase:t page2 p:default-keys-1:h)
  ?>  ?=(^ -.coin2)
  =^  last-page  con  (add-n-pages:h 101 con default-retain:h)
  ::  two inputs -> one output
  =/  inp1=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin1 s:default-keys-1:h)
  =/  inp2=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin2 s:default-keys-1:h)
  =/  ips=inputs:t  (multi:new:v0:inputs:t ~[inp1 inp2])
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)
    (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    ?|  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin2))
    ==
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  ?>  ?=(^ -.new-note)
  =/  new-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note))
  %+  expect-eq
    !>  [%.n %.y]
  !>  [old-in-balance new-in-balance]
::
++  test-three-to-one-utxo-spend
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =^  page2=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =^  page3=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::

  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =/  coin2=coinbase:t  (new:v0:coinbase:t page2 p:default-keys-1:h)
  ?>  ?=(^ -.coin2)
  =/  coin3=coinbase:t  (new:v0:coinbase:t page3 p:default-keys-1:h)
  ?>  ?=(^ -.coin3)
  =^  last-page  con  (add-n-pages:h 101 con default-retain:h)
  ::  three inputs -> one output
  =/  inp1=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin1 s:default-keys-1:h)
  =/  inp2=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin2 s:default-keys-1:h)
  =/  inp3=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin3 s:default-keys-1:h)
  =/  ips=inputs:t  (multi:new:v0:inputs:t ~[inp1 inp2 inp3])
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    ?|  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin2))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin3))
    ==
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  ?>  ?=(^ -.new-note)
  =/  new-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note))
  %+  expect-eq
    !>  [%.n %.y]
  !>  [old-in-balance new-in-balance]
::
++  test-one-to-two-utxo-spend
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =^  last-page=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  seed1=seed:t
    %*  .  *seed:t
      gift  (dec assets.coin1)
      recipient  p:default-keys-2:h
      parent-hash  (hash:nnote:t coin1)
    ==
  =/  seed2=seed:t
    %*  .  *seed:t
      gift  1
      recipient  p:default-keys-3:h
      parent-hash  (hash:nnote:t coin1)
    ==
  ::  one inputs -> two outputs
  =/  inp1=$>(%0 input:t)
    ($:new:v0:input:t coin1 (~(gas z-in *seeds:t) ~[seed1 seed2]) 0 s:default-keys-1:h)
  =/  ips=inputs:t  (new:v0:inputs:t inp1)
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note1=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  =/  new-note2=nnote:t
    note:(~(got z-by +.outs) p:default-keys-3:h)
  ?>  ?=(^ -.new-note1)
  ?>  ?=(^ -.new-note2)
  =/  new-in-balance=?
    ?&  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note2))
    ==
  %+  expect-eq
    !>  [%.n %.y (dec assets.coin1) 1]
  !>  [old-in-balance new-in-balance assets.new-note1 assets.new-note2]
::
++  test-one-to-three-utxo-spend
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =^  last-page=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  seed1=seed:t
    %*  .  *seed:t
      gift  (sub assets.coin1 3)
      recipient  p:default-keys-2:h
      parent-hash  (hash:nnote:t coin1)
    ==
  =/  seed2=seed:t
    %*  .  *seed:t
      gift  1
      recipient  p:default-keys-3:h
      parent-hash  (hash:nnote:t coin1)
    ==
  =/  seed3=seed:t
    %*  .  *seed:t
      gift  2
      recipient  p:default-keys-1:h
      parent-hash  (hash:nnote:t coin1)
    ==
  ::  one input -> three outputs
  =/  inp1=$>(%0 input:t)  ($:new:v0:input:t coin1 (~(gas z-in *seeds:t) ~[seed1 seed2 seed3]) 0 s:default-keys-1:h)
  =/  ips=inputs:t  (new:v0:inputs:t inp1)
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ~&  >>  constants+constants
  =/  valid=(reason ~)  (~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ?.  -.valid
    ~&  >>  [%failed-reason +:valid]  !!
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note1=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  =/  new-note2=nnote:t
    note:(~(got z-by +.outs) p:default-keys-3:h)
  =/  new-note3=nnote:t
    note:(~(got z-by +.outs) p:default-keys-1:h)
  ?>  ?=(^ -.new-note1)
  ?>  ?=(^ -.new-note2)
  ?>  ?=(^ -.new-note3)
  =/  new-in-balance=?
    ?&  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note2))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note3))
    ==
  %+  expect-eq
    !>  [%.n %.y (sub assets.coin1 3) 1 2]
  !>  :*  old-in-balance
          new-in-balance
          assets.new-note1
          assets.new-note2
          assets.new-note3
      ==
::
++  test-two-to-two-utxo-sp  ::
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =^  page2=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin2=coinbase:t  (new:v0:coinbase:t page2 p:default-keys-1:h)
  ?>  ?=(^ -.coin2)
  =^  last-page=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  ::  one inputs -> two outputs
  =/  inp1=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin1 s:default-keys-1:h)
  =/  inp2=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-3:h coin2 s:default-keys-1:h)
  =/  ips=inputs:t  (multi:new:v0:inputs:t ~[inp1 inp2])
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)
    (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    ?|  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin2))
    ==
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note1=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  =/  new-note2=nnote:t
    note:(~(got z-by +.outs) p:default-keys-3:h)
  ?>  ?=(^ -.new-note1)
  ?>  ?=(^ -.new-note2)
  =/  new-in-balance=?
    ?&  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note2))
    ==
  %+  expect-eq
    !>  [%.n %.y assets.coin1 assets.coin2]
  !>  [old-in-balance new-in-balance assets.new-note1 assets.new-note2]
::
++  test-two-to-three-utxo-spend
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =^  page2=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin2=coinbase:t  (new:v0:coinbase:t page2 p:default-keys-1:h)
  ?>  ?=(^ -.coin2)
  =^  last-page=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  seed2=seed:t
    %*  .  *seed:t
      gift  (dec assets.coin2)
      recipient  p:default-keys-3:h
      parent-hash  (hash:nnote:t coin2)
    ==
  =/  seed3=seed:t
    %*  .  *seed:t
      gift  1
      recipient  p:default-keys-1:h
      parent-hash  (hash:nnote:t coin2)
    ==
  ::  two inputs -> three outputs
  =/  inp1=$>(%0 input:t)
    (simple-from-note:new:v0:input:t p:default-keys-2:h coin1 s:default-keys-1:h)
  =/  inp2=$>(%0 input:t)  ($:new:v0:input:t coin2 (~(gas z-in *seeds:t) ~[seed2 seed3]) 0 s:default-keys-1:h)
  =/  ips=inputs:t  (multi:new:v0:inputs:t ~[inp1 inp2])
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    ?|  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin2))
    ==
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note1=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  =/  new-note2=nnote:t
    note:(~(got z-by +.outs) p:default-keys-3:h)
  =/  new-note3=nnote:t
    note:(~(got z-by +.outs) p:default-keys-1:h)
  ?>  ?=(^ -.new-note1)
  ?>  ?=(^ -.new-note2)
  ?>  ?=(^ -.new-note3)
  =/  new-in-balance=?
    ?&  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note2))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note3))
    ==
  %+  expect-eq
    !>  [%.n %.y assets.coin1 (dec assets.coin2) 1]
  !>  :*  old-in-balance
          new-in-balance
          assets.new-note1
          assets.new-note2
          assets.new-note3
      ==
::
++  test-three-to-two-utxo-spend
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =^  page2=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin2=coinbase:t  (new:v0:coinbase:t page2 p:default-keys-1:h)
  ?>  ?=(^ -.coin2)
  =^  page3=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin3=coinbase:t  (new:v0:coinbase:t page3 p:default-keys-1:h)
  ?>  ?=(^ -.coin3)
  =^  last-page=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  ::  three inputs -> two outputs
  =/  inp1=$>(%0 input:t)  (simple-from-note:new:v0:input:t p:default-keys-2:h coin1 s:default-keys-1:h)
  =/  inp2=$>(%0 input:t)  (simple-from-note:new:v0:input:t p:default-keys-3:h coin2 s:default-keys-1:h)
  =/  inp3=$>(%0 input:t)  (simple-from-note:new:v0:input:t p:default-keys-3:h coin3 s:default-keys-1:h)
  =/  ips=inputs:t  (multi:new:v0:inputs:t ~[inp1 inp2 inp3])
  =/  raw=raw-tx:t  (from-inputs:v0:raw-tx:t ips)
  ::
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  =tx:t  (new:tx:t raw ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    ?|  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin2))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin3))
    ==
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note1=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  =/  new-note2=nnote:t
    note:(~(got z-by +.outs) p:default-keys-3:h)
  ?>  ?=(^ -.new-note1)
  ?>  ?=(^ -.new-note2)
  =/  new-in-balance=?
    ?&  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note2))
    ==
  %+  expect-eq
    !>  [%.n %.y assets.coin1 (add assets.coin2 assets.coin3)]
  !>  :*  old-in-balance
          new-in-balance
          assets.new-note1
          assets.new-note2
      ==
::
++  test-two-valid-transactions-in-one-block
  =/  con=consensus-state  initial-consensus-state:h
  =^  page1=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin1=coinbase:t  (new:v0:coinbase:t page1 p:default-keys-1:h)
  ?>  ?=(^ -.coin1)
  =^  page2=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  coin2=coinbase:t  (new:v0:coinbase:t page2 p:default-keys-1:h)
  ?>  ?=(^ -.coin2)
  =^  last-page=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  ::  first transaction: coin1 to keys-2
  =/  raw1=raw-tx:t
    (simple-from-note:new:raw-tx:v0:t p:default-keys-2:h coin1 s:default-keys-1:h)
  ::  second transaction: coin2 to keys-3
  =/  raw2=raw-tx:t
    (simple-from-note:new:raw-tx:v0:t p:default-keys-3:h coin2 s:default-keys-1:h)
  ::  create new page with both transactions
  =/  new-page=page:t  (make-empty-page:h last-page)
  =/  tx1=tx:t  (new:tx:t raw1 ~(height get:page:t new-page))
  =/  tx2=tx:t  (new:tx:t raw2 ~(height get:page:t new-page))
  ?>  ?=(^ -.raw-tx.tx1)
  ?>  ?=(^ -.raw-tx.tx2)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(gas z-in *(z-set tx-id:t)) ~[id.raw-tx.tx1 id.raw-tx.tx2])
      ==
    %=  new-page
      tx-ids  (~(gas z-in *(z-set tx-id:t)) ~[id.raw-tx.tx1 id.raw-tx.tx2])
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx1)
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx2)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::  validate and add the new page
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  ::  check balances
  =/  old-in-balance=?
    ?|  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t coin2))
    ==
  =/  outs1=outputs:t  ~(outputs get:tx:t tx1)
  =/  outs2=outputs:t  ~(outputs get:tx:t tx2)
  ?>  ?=(%0 -.outs1)
  ?>  ?=(%0 -.outs2)
  =/  new-note1=nnote:t
    note:(~(got z-by +.outs1) p:default-keys-2:h)
  =/  new-note2=nnote:t
    note:(~(got z-by +.outs2) p:default-keys-3:h)
  ?>  ?=(^ -.new-note1)
  ?>  ?=(^ -.new-note2)
  =/  new-in-balance=?
    ?&  (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note1))
        (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note2))
    ==
  %+  expect-eq
    !>  [%.n %.y assets.coin1 assets.coin2]
  !>  :*  old-in-balance
          new-in-balance
          assets.new-note1
          assets.new-note2
      ==
::
++  test-add-tx-to-candidate-block
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  ::  create a new empty candidate block
  =/  min=mining-state  initial-mining-state:h
  =.  min  (~(heard-new-block dmin min der constants) con *@da)
  =/  raw=raw-tx:t  (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h)
  ?>  ?=(^ -.raw)
  =.  min  (~(heard-new-tx dmin min der constants) raw)
  %+  expect-eq
    !>(%.y)
  !>((~(has z-in ~(tx-ids get:page:t candidate-block.min)) ~(id get:raw-tx:t raw)))
::
++  test-fail-add-double-spend-to-candidate-block
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  ::  create a new empty candidate block
  =/  min=mining-state  initial-mining-state:h
  =.  min  (~(heard-new-block dmin min der constants) con *@da)
  ::
  =/  raw1=raw-tx:t  (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h)
  =/  raw2=raw-tx:t  (make-default-coinbase-raw-tx:v0:h p:default-keys-3:h)
  ?>  ?=(^ -.raw1)
  ?>  ?=(^ -.raw2)
  =.  min  (~(heard-new-tx dmin min der constants) raw1)
  =.  min  (~(heard-new-tx dmin min der constants) raw2)
  %+  expect-eq
    !>  [%.y %.n]
  !>  :-  (~(has z-in ~(tx-ids get:page:t candidate-block.min)) ~(id get:raw-tx:t raw1))
      (~(has z-in ~(tx-ids get:page:t candidate-block.min)) ~(id get:raw-tx:t raw2))
::
::  a transaction with no inputs should fail unless its a coinbase. this
::  tests that such a tx will be rejected by the miner module
++  test-zero-utxo-tx-fail-candidate-block
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  min=mining-state  initial-mining-state:h
  =.  min  (~(heard-new-block dmin min der constants) con *@da)
  ::
  =|  raw=raw-tx:v0:t
  =/  expect-min  min
  =.  min  (~(heard-new-tx dmin min der constants) raw)
  %+  expect-eq  :: mining state should not change
    !>(expect-min)
  !>(min)
::
::  if we hear a zero utxo tx over the wire, it should be rejected
++  test-zero-utxo-tx-fail-validation
  =|  raw=raw-tx:v0:t
  ?>  ?=(^ -.raw)
  =.  id.raw  (compute-id:raw-tx:t raw)
  %+  expect-eq
    !>(%.n)
  :: this is the first check in +heard-tx in the kernel after the id check
  !>((validate:raw-tx:t raw))
::
::  if we hear a block with a zero utxo tx, we should reject it
++  test-zero-utxo-tx-block-reject
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =|  raw=raw-tx:v0:t
  ?>  ?=(^ -.raw)
  =.  id.raw  (compute-id:raw-tx:t raw)
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =/  tac=(reason tx-acc:t)
    (~(validate-page-with-txs dcon con der constants) new-page)
  %+  expect-eq  !>(%.n)
  !>(-:tac)
::
++  test-valid-signed-spend
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-2:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-1:h
  %-  expect
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-valid-2-of-2-multisig-input
  =/  =sig:t
    (join:sig:t 2 ~[p:default-keys-1:h p:default-keys-2:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-2:h
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-1:h
  %-  expect
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-valid-1-of-3-multisig-input
  =/  =sig:t
    (join:sig:t 1 ~[p:default-keys-1:h p:default-keys-2:h p:default-keys-3:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  %-  expect
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-valid-2-of-3-multisig-input
  =/  =sig:t
    (join:sig:t 2 ~[p:default-keys-1:h p:default-keys-2:h p:default-keys-3:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-2:h
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  %-  expect
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-valid-1-of-3-multisig-input-oversign
  =/  =sig:t
    (join:sig:t 1 ~[p:default-keys-1:h p:default-keys-2:h p:default-keys-3:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-1:h
  %-  expect
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-valid-1-of-3-multisig-input-double-sign
  =/  =sig:t
    (join:sig:t 1 ~[p:default-keys-1:h p:default-keys-2:h p:default-keys-3:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  %-  expect
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-invalid-2-of-3-multisig-input
  =/  =sig:t
    (join:sig:t 2 ~[p:default-keys-1:h p:default-keys-2:h p:default-keys-3:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  %+  expect-eq
    !>(%.n)
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-invalid-1-of-2-multisig-input-wrong-sig
  =/  =sig:t
    (join:sig:t 1 ~[p:default-keys-1:h p:default-keys-2:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  %+  expect-eq
    !>(%.n)
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-invalid-1-of-2-multisig-input-right-and-wrong-sig
  =/  =sig:t
    (join:sig:t 1 ~[p:default-keys-1:h p:default-keys-2:h])
  =/  new-page=page:t  (make-empty-page-multisig:h default-genesis-page:h sig)
  =/  =coinbase:t  (new:v0:coinbase:t new-page sig)
  ?>  ?=(^ -.coinbase)
  =/  sen=spend:t
    (simple-from-note:new:spend:t p:default-keys-3:h coinbase)
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-3:h
  =.  sen
    %+  sign:spend:t
      sen
    s:default-keys-1:h
  %+  expect-eq
    !>(%.n)
  !>  %+  verify:spend:t
        sen
      coinbase
::
++  test-multisig-valid-output-2-of-2
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  ::
  =/  =sig:t
    (join:sig:t 2 ~[p:default-keys-1:h p:default-keys-2:h])
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h sig) 102)
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t make-default-coinbase:v0:h))
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note=nnote:t
    note:(~(got z-by +.outs) sig)
  ?>  ?=(^ -.new-note)
  =/  new-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note))
  %+  expect-eq
    !>  [%.n %.y]
  !>  [old-in-balance new-in-balance]
::
++  test-multisig-valid-output-2-of-3
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  ::
  =/  =sig:t
    (join:sig:t 2 ~[p:default-keys-1:h p:default-keys-2:h p:default-keys-3:h])
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h sig) 102)
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  ::
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)  (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t make-default-coinbase:v0:h))
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note=nnote:t
    note:(~(got z-by +.outs) sig)
  ?>  ?=(^ -.new-note)
  =/  new-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note))
  %+  expect-eq
    !>  [%.n %.y]
  !>  [old-in-balance new-in-balance]
::  reject a block whose timestamp is older than the median of the last 11 blocks
++  test-reject-block-old
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  new-timestamp  (sub ~(timestamp get:page:t par) (mul 60 240))
  =.  new-page
    ?^  -.new-page
      new-page(timestamp new-timestamp)
    new-page(timestamp new-timestamp)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
::  reject a block whose timestamp is more than 2 hours in the future
++  test-reject-block-time-traveler
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  new-timestamp  (add ~(timestamp get:page:t par) (mul 60 131))  :: 131 minutes in the future
  =.  new-page
    ?^  -.new-page
      new-page(timestamp new-timestamp)
    new-page(timestamp new-timestamp)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
++  test-reject-block-epoch-counter
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  new-epoch-counter  +(~(epoch-counter get:page:t new-page))
  =.  new-page
    ?^  -.new-page
      new-page(epoch-counter new-epoch-counter)
    new-page(epoch-counter new-epoch-counter)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
++  test-reject-block-parent-epoch-counter
  =/  con=consensus-state  (initial-consensus-state-custom:h constants)
  =^  par=page:t  con  (add-n-pages:h (dec blocks-per-epoch:constants) con default-retain:h)
  =/  new-epoch-counter-par  blocks-per-epoch:constants
  =.  par
    ?^  -.par
      par(epoch-counter new-epoch-counter-par)
    par(epoch-counter new-epoch-counter-par)
  =/  old-digest  ~(digest get:page:t par)
  =/  new-digest-par  (compute-digest:page:t par)
  =.  par
    ?^  -.par
      par(digest new-digest-par)
    par(digest new-digest-par)
  =.  blocks.con  (~(put h-by blocks.con) ~(digest get:page:t par) (to-local-page:page:t par))
  =/  min  (~(got h-by min-timestamps.con) old-digest)
  =.  min-timestamps.con  (~(put h-by min-timestamps.con) ~(digest get:page:t par) min)
  =/  new-page=page:t  (make-empty-page:h par)
  ::  this is to fake the check-target since make-empty-page doesn't know
  ::  about epoch boundaries
  =.  targets.con  (~(put h-by targets.con) ~(digest get:page:t par) ~(target get:page:t new-page))
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
++  test-reject-block-target
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  new-target  (chunk:bignum (add (merge:bignum ~(target get:page:t new-page)) 1))
  =.  new-page
    ?^  -.new-page
      new-page(target new-target)
    new-page(target new-target)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
++  test-reject-block-height
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  new-height  +(~(height get:page:t new-page))
  =.  new-page
    ?^  -.new-page
      new-page(height new-height)
    new-page(height new-height)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
++  test-reject-block-heaviness
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  new-accumulated-work  (chunk:bignum +((merge:bignum ~(accumulated-work get:page:t new-page))))
  =.  new-page
    ?^  -.new-page
      new-page(accumulated-work new-accumulated-work)
    new-page(accumulated-work new-accumulated-work)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  %+  expect-eq  !>(%.n)
  !>(-:(~(validate-page-without-txs dcon con der constants) new-page (add 600 ~(timestamp get:page:t par))))
::
++  test-reject-tx-digest
  =/  raw=raw-tx:t  (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h)
  ?>  ?=(^ -.raw)
  =.  id.raw  *tx-id:t
  %+  expect-eq  !>(%.n)
  !>((validate:raw-tx:t raw))
::
++  test-reject-tx-inputs-bad-sig
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =/  seed1=seed:t
    (from-note:simple:new:seed:t p:default-keys-2:h coinbase)
  =/  inp=$>(%0 input:t)  :: sign with wrong key
    ($:new:v0:input:t coinbase (~(put z-in *seeds:t) seed1) 0 s:default-keys-2:h)
  %+  expect-eq  !>(%.n)
  !>((validate:v0:input:t inp))
::
++  test-reject-tx-inputs-bad-input
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =/  seed1=seed:t
    %*  .  *seed:t
      gift  assets.coinbase
      recipient  p:default-keys-2:h
      parent-hash  (hash:nnote:t coinbase)
    ==
  =/  seed2=seed:t
    %*  .  *seed:t
      gift  0
      recipient  p:default-keys-3:h
      parent-hash  (hash:nnote:t coinbase)
    ==
  =/  inp=$>(%0 input:t)
    ($:new:v0:input:t coinbase (~(put z-in *seeds:t) seed1) 0 s:default-keys-1:h)
  ::
  ::  input is bad because signature only commits to seed1 and not seed1 and seed2
  ?>  ?=(%0 -.inp)
  =.  seeds.spend.inp  (~(put z-in seeds.spend.inp) seed2)
  =/  ips=inputs:t  (new:v0:inputs:t inp)
  %+  expect-eq  !>(~)
  !>((mole |.((from-inputs:v0:raw-tx:t ips))))
::
++  test-reject-tx-timelock
  =/  raw=raw-tx:t  (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h)
  ?>  ?=(^ -.raw)
  =.  timelock-range.raw  *timelock-range:t
  ?>  ?=(^ -.raw)
  =.  id.raw  (compute-id:raw-tx:t raw)
  %+  expect-eq  !>(%.n)
  !>((validate:raw-tx:t raw))
::
++  test-reject-tx-fees
  =/  raw=raw-tx:t  (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h)
  ?>  ?=(^ -.raw)
  =.  total-fees.raw  1
  ?>  ?=(^ -.raw)
  =.  id.raw  (compute-id:raw-tx:t raw)
  %+  expect-eq  !>(%.n)
  !>((validate:raw-tx:t raw))
::
++  test-seed-simple-from-note-with-choice-refund
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =.  coinbase  coinbase(assets 3)
  =/  seds=seeds:t
    %:  with-choice:simple-from-note-with-refund:new:seeds:t
        recipient=p:default-keys-2:h
        gift=1
        fee=0
        note=coinbase
        refund-address=p:default-keys-3:h
    ==
  =/  seedz=(list seed:t)  ~(tap z-in seds)
  ?>  =(2 (lent seedz))
  ::
  ::  All of this code below is to determine which seed is the refund
  ::  and which seed is the gift.
  =/  sed1=seed:t  (snag 0 seedz)
  =/  sed2=seed:t  (snag 1 seedz)
  =/  [num-refund=@ refund-seed=seed:t]
    ?:  =(recipient.sed1 p:default-keys-3:h)
      [%1 sed1]
    ?:  =(recipient.sed2 p:default-keys-3:h)
      [%2 sed2]
    !!
  =/  gift-seed
    ?:  ?=(%1 num-refund)
      sed2
    sed1
  ::  Now that we determined which is the refund and gift, we check
  ::  for correctness.
  %+  expect-eq
    !>(%.y)
  !>  ?&  =(gift:refund-seed 2)
          =(parent-hash:refund-seed (hash:nnote:t coinbase))
          =(recipient.refund-seed p:default-keys-3:h)
        ::
          =(gift:gift-seed 1)
          =(parent-hash:gift-seed (hash:nnote:t coinbase))
          =(recipient.gift-seed p:default-keys-2:h)
      ==
::
++  test-seed-simple-from-note-with-choice-no-refund
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =.  coinbase  coinbase(assets 1)
  =/  seds=seeds:t
    %:  with-choice:simple-from-note-with-refund:new:seeds:t
      recipient=p:default-keys-2:h
      gift=1
      fee=0
      note=coinbase
      refund-address=p:default-keys-3:h
    ==
  =/  seedz=(list seed:t)  ~(tap z-in seds)
  ?>  =(1 (lent seedz))
  =/  sed=seed:t  (head seedz)
  %+  expect-eq
    !>(%.y)
  !>  ?&  =(gift:sed 1)
          =(parent-hash:sed (hash:nnote:t coinbase))
          =(recipient.sed p:default-keys-2:h)
      ==
::
++  test-seeds-with-invalid-source
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =.  coinbase  coinbase(assets 3)
  =/  recipient2  p:default-keys-2:h
  =/  recipient3  p:default-keys-3:h
  =/  sed1=seed:t
    %:  simple:new:seed:t
        recipient=recipient2
        gift=1
        hash=(hash:nnote:t coinbase)
    ==
  =.  sed1  sed1(output-source `[(hash:seed:t sed1) %.n])
  =/  sed2=seed:t
    %:  simple:new:seed:t
        recipient=recipient2
        gift=2
        hash=(hash:nnote:t coinbase)
    ==
  =.  sed2  sed2(output-source `[(hash:seed:t sed1) %.n])
  =/  seds=seeds:t  (new:seeds:t ~[sed1 sed2])
  =/  inp=$>(%0 input:t)  ($:new:v0:input:t coinbase seds 0 s:default-keys-1:h)
  =/  inps=inputs:t  (new:v0:inputs:t inp)
  =/  succ=(unit raw-tx:t)  (mole |.((from-inputs:v0:raw-tx:t inps)))
  ?~  succ
    !!
  =/  transaction=(unit tx:t)  (mole |.((new:tx:t u.succ 1)))
  ?~  transaction
    !!
  %+  expect-eq
    !>(%.n)
  !>((validate:tx:t u.transaction))
::
++  test-seeds-with-valid-source
  =/  =coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinbase)
  =.  coinbase  coinbase(assets 3)
  =/  recipient2  p:default-keys-2:h
  =/  recipient3  p:default-keys-3:h
  =/  sed1=seed:t
    %:  simple:new:seed:t
        recipient=recipient2
        gift=1
        hash=(hash:nnote:t coinbase)
    ==
  =/  sed2=seed:t
    %:  simple:new:seed:t
        recipient=recipient2
        gift=2
        hash=(hash:nnote:t coinbase)
    ==
  =/  seds=seeds:t  (new:seeds:t ~[sed1 sed2])
  =.  sed1  sed1(output-source `[(hash:seeds:t seds) %.n])
  =.  sed2  sed2(output-source `[(hash:seeds:t seds) %.n])
  =/  inp=$>(%0 input:t)  ($:new:v0:input:t coinbase seds 0 s:default-keys-1:h)
  =/  inps=inputs:t  (new:v0:inputs:t inp)
  =/  succ=(unit raw-tx:t)  (mole |.((from-inputs:v0:raw-tx:t inps)))
  ?~  succ
    !!
  =/  transaction=(unit tx:t)  (mole |.((new:tx:t u.succ 1)))
  ?~  transaction
    !!
  %+  expect-eq
    !>(%.y)
  !>((validate:tx:t u.transaction))
::
++  test-spend-fee
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 101 con default-retain:h)
  ::
  =/  new-page=page:t  (make-empty-page:h par)
  =/  coinb=coinbase:t  make-default-coinbase:v0:h
  ?>  ?=(^ -.coinb)
  =/  fees=coins:t  1
  =/  raw=raw-tx:t
    %:  with-refund:simple-from-note:new:raw-tx:v0:t
        recipient=p:default-keys-2:h
        gift=1
        fees
        not=coinb
        sk=s:default-keys-1:h
    ==
  =/  =tx:t  (new:tx:t raw 102)
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =/  total-coinbase-assets=coins:t
    (add (emission-calc:coinbase:t ~(height get:page:t new-page)) ~(total-fees get:tx:t tx))
  =.  new-page
    ?^  -.new-page
      %=  new-page
        coinbase  (new:v0:coinbase-split:t total-coinbase-assets default-keys-1-share:h)
      ==
    %=  new-page
      coinbase  (new:v1:coinbase-split:t total-coinbase-assets default-keys-1-share-v1:h)
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ?>  -:(~(validate-page-without-txs dcon con der constants) new-page ~(timestamp get:page:t new-page))
  =/  tac  (~(validate-page-with-txs dcon con der constants) new-page)
  ?:  ?=(%.n -.tac)
    (expect !>(%.n))
  =.  con  (~(accept-page dcon con der constants) new-page +.tac *@da)
  =.  con  (~(update-heaviest dcon con der constants) new-page)
  =/  old-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t make-default-coinbase:v0:h))
  =/  outs=outputs:t  ~(outputs get:tx:t tx)
  ?>  ?=(%0 -.outs)
  =/  new-note=nnote:t
    note:(~(got z-by +.outs) p:default-keys-2:h)
  ?>  ?=(^ -.new-note)
  =/  new-in-balance=?
    (~(has h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-note))
  =/  new-coinb=coinbase:t
    (new:v0:coinbase:t new-page p:default-keys-1:h)
  %+  expect-eq
    !>  :*  %.n
            %.y
            new-coinb
            (~(got z-by =<(+ ~(coinbase get:page:t new-page))) p:default-keys-1:h)
        ==
  !>  :*  old-in-balance
          new-in-balance
          (~(got h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-coinb))
          assets:(~(got h-bi balance.con) ~(digest get:page:t new-page) ~(name get:nnote:t new-coinb))
      ==
::
::  given i hear tx at height two, when i hear one more page, pending
::  state is unchanged
++  test-pending-tx-retain-1-page
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  we hear a new tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  =/  expect-pending-blocks  pending-blocks.con
  =^  par=page:t  con  (add-n-pages:h 1 con (some 20))
  %+  expect-eq
    !>(expect-pending-blocks)
  !>(pending-blocks.con)
::
::  given i hear tx at height two, when i hear one fewer page than the
::  tx GC window, pending state is unchanged
++  test-pending-tx-retain-before-gc
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  we hear a new tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  =/  expect-raw-txs  raw-txs.con
  =/  expect-excluded-txs  excluded-txs.con
  ::  add one fewer page than the tx gc window to hit edge case
  =^  new-page=page:t  con  (add-n-pages:h (dec default-tx-gc-retain:h) con default-retain:h)
  ;:  weld
    %+  expect-eq
      !>(expect-raw-txs)
    !>(raw-txs.con)
  ::
    %+  expect-eq
      !>(expect-excluded-txs)
    !>(excluded-txs.con)
  ==
::
::  given i hear tx at height two, when i hear the tx GC window's worth
::  of pages, pending state is the same as it was before i heard that tx.
++  test-pending-tx-dont-retain-at-gc
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  we hear a new tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  ::
  =/  expect-raw-txs  raw-txs.con
  =/  expect-excluded-txs  excluded-txs.con
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  ::  add the tx gc window's worth of pages to hit the edge
  =^  new-page=page:t  con  (add-n-pages:h default-tx-gc-retain:h con default-retain:h)
  ;:  weld
    %+  expect-eq
      !>(expect-raw-txs)
    !>(raw-txs.con)
  ::
    %+  expect-eq
      !>(expect-excluded-txs)
    !>(excluded-txs.con)
  ==
::
::  given i hear tx at height two and our pending tx retainment policy is
::  to get rid of them every time i hear a new block, when i hear a new block
::  the pending state is as it was before i heard the tx.
++  test-pending-tx-never-retain
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  we hear a new tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  ::
  =/  expect-raw-txs  raw-txs.con
  =/  expect-excluded-txs  excluded-txs.con
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  =^  new-page=page:t  con  (add-n-pages:h 1 con (some 0))
  ;:  weld
    %+  expect-eq
      !>(expect-raw-txs)
    !>(raw-txs.con)
  ::
    %+  expect-eq
      !>(expect-excluded-txs)
    !>(excluded-txs.con)
  ==
::
:::  retain=~ leaves pending-block retention unbounded, but excluded txs still
:::  use a bounded safety lease.
++  test-pending-tx-no-drop-retain-before-safety-gc
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  we hear a new tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  =/  expect-raw-txs  raw-txs.con
  =/  expect-excluded-txs  excluded-txs.con
  =^  par=page:t  con  (add-n-pages:h +(default-tx-gc-retain:h) con ~)
  ;:  weld
    %+  expect-eq
      !>(expect-raw-txs)
    !>(raw-txs.con)
  ::
    %+  expect-eq
      !>(expect-excluded-txs)
    !>(excluded-txs.con)
  ==

:::
:::  A configured retention window longer than the default safety lease controls
:::  tx expiry.
++  test-pending-tx-honors-configured-retain
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  =/  retain=(unit @)  (some 30)
  ::  we hear a new tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  =/  before-raw-txs  raw-txs.con
  =/  before-excluded-txs  excluded-txs.con
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw)
  =/  live-raw-txs  raw-txs.con
  =/  live-excluded-txs  excluded-txs.con
  ::  The tx is older than 20 blocks but inside the configured 30-block
  ::  window.
  =^  par=page:t  con  (add-n-pages:h 25 con retain)
  =/  kept-raw-txs  raw-txs.con
  =/  kept-excluded-txs  excluded-txs.con
  =^  par=page:t  con  (add-n-pages:h 5 con retain)
  ;:  weld
    %+  expect-eq
      !>(live-raw-txs)
    !>(kept-raw-txs)
  ::
    %+  expect-eq
      !>(live-excluded-txs)
    !>(kept-excluded-txs)
  ::
    %+  expect-eq
      !>(before-raw-txs)
    !>(raw-txs.con)
  ::
    %+  expect-eq
      !>(before-excluded-txs)
    !>(excluded-txs.con)
  ==
::
++  test-pending-reject-inputs-in-spent-by
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  tx1=tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw1=raw-tx:t  raw-tx.tx1
  =/  tx2=tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-3:h) 2)
  =/  raw2=raw-tx:t  raw-tx.tx2
  ::
  ::  heard first tx
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw1)
  ::
  ::  heard second tx with same input
  %+  expect-eq
    !>(%.y)
  !>((~(inputs-spent dcon con der constants) raw2))
::
++  test-pending-reject-inputs-not-in-balance
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  raw=raw-tx:t  make-rogue-tx:v0:h
  ::
  ::  heard tx
  %+  expect-eq
    !>(%.n)
  !>((~(inputs-in-heaviest-balance dcon con der constants) raw))
::
++  test-pending-accepts-inputs-not-in-spent-by
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  tx=tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  ::
  ::  heard tx
  %+  expect-eq
    !>(%.n)
  !>((~(inputs-spent dcon con der constants) raw))
::
++  test-pending-accepts-inputs-in-heaviest-balance
  =/  con=consensus-state  initial-consensus-state:h
  =^  new-page=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  =/  raw=raw-tx:t  raw-tx.tx
  ::
  ::  heard tx
  %+  expect-eq
    !>(%.y)
  !>((~(inputs-in-heaviest-balance dcon con der constants) raw))
::
++  test-remove-pending-block
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  make tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  ::
  ::  make new page with tx
  =/  new-page=page:t  (make-empty-page:h par)
  ?>  ?=(^ -.raw-tx.tx)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  ::
  =/  expect-con  con
  ::  add block to pending state
  =^  miss  con  (~(add-pending-block dcon con der constants) new-page)
  ::  remove block from pending state
  =.  con  (~(reject-pending-block dcon con der constants) ~(digest get:page:t new-page))
  ::
  %+  expect-eq
    !>  expect-con
  !>  con
::
++  test-find-ready-blocks
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  make tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  ::
  ::  make new page with tx
  ?>  ?=(^ -.raw-tx.tx)
  =/  new-page=page:t  (make-empty-page:h par)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  ::
  ::  add block to pending state
  =^  miss  con  (~(add-pending-block dcon con der constants) new-page)
  ::
  ::  add tx to pending state
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx)
  ::
  =/  expect-ready
    ~[~(digest get:page:t new-page)]
  ::
  %+  expect-eq
    !>  expect-ready
  !>  ready
::
++  test-no-ready-blocks
  =/  con=consensus-state  initial-consensus-state:h
  =^  par=page:t  con  (add-n-pages:h 1 con default-retain:h)
  ::  make tx
  =/  =tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-2:h) 2)
  ::
  =/  tx2=tx:t  (new:tx:t (make-default-coinbase-raw-tx:v0:h p:default-keys-3:h) 2)
  ?>  ?=(^ -.raw-tx.tx)
  ::
  ::  make new page with tx
  =/  new-page=page:t  (make-empty-page:h par)
  =.  new-page
    ?^  -.new-page
      %=  new-page
        tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
      ==
    %=  new-page
      tx-ids  (~(put z-in *(z-set tx-id:t)) ~(id get:raw-tx:t raw-tx.tx))
    ==
  =.  new-page
    ?^  -.new-page
      %=  new-page
        digest  (compute-digest:page:t new-page)
      ==
    %=  new-page
      digest  (compute-digest:page:t new-page)
    ==
  ::
  ::  add block to pending state
  =^  miss  con  (~(add-pending-block dcon con der constants) new-page)
  ::
  ::
  =^  ready  con  (~(add-raw-tx dcon con der constants) raw-tx.tx2)
  ::
  ::  dont add tx to pending state
  =/  expect-ready  ~
  ::
  %+  expect-eq
    !>  expect-ready
  !>  ready
::
::  +test-target-adjustment:
::
::    practically this is just a test for +chunk and +merge right now,
::    since we're just testing a formula of the form (p*d)/e. but
::    once we compute adjustments using bignum arithmetic, this will
::    be more useful.
++  test-target-adjustment
  |^
  =/  bn  bignum
  =/  compute-target-atoms-samples=(list [@ @])
    %-  zing
    %+  turn  epoch-durs-list:h
    |=  dur=@
    %+  turn  initial-atom-targets:h
    |=(tar=@ dur^tar)
  =/  compute-targets-bignum-samples=(list [@ bignum:bn])
    %-  zing
    %+  turn  epoch-durs-list:h
    |=  dur=@
    %+  turn  initial-bignum-targets:h
    |=(tar=bignum:bn dur^tar)
  ::
  ::  turn expected targets into atoms
  =/  expect-target-atoms=(list @)
    (turn compute-target-atoms-samples compute-target-raw-atom)
  =/  actual-target-bignums=(list @)
    %+  turn
      %+  turn  compute-targets-bignum-samples
      ~(compute-target-raw dcon *consensus-state der constants)
    merge:bn
  =/  bad  (compare-lists expect-target-atoms actual-target-bignums)
  %+  expect-eq  !>(expect-target-atoms)
  !>(actual-target-bignums)
  ::
  ::  +compute-target-raw-atom
  ::
  ::    same as +compute-target but done entirely with atoms
  ++  compute-target-raw-atom
    |=  [epoch-dur=@ prev-target=@]
    ^-  @
    =/  capped-epoch-dur=@
      ?:  (lth epoch-dur quarter-ted:t)
        quarter-ted:t
      ?:  (gth epoch-dur quadruple-ted:t)
        quadruple-ted:t
      epoch-dur
    =/  next-target=@
      %+  div
        (mul prev-target capped-epoch-dur)
      target-epoch-duration:t
    ?:  (gth next-target max-target-atom:t)
      max-target-atom:t
    next-target
  ::
  ++  compare-lists
    |=  [a=(list @) b=(list @)]
    ?>  =((lent a) (lent b))
    =|  i=@
    =|  bad=(list @)
    |-
    ?~  a  bad
    ?~  b  bad
    ?:  =(i.a i.b)
      $(a t.a, b t.b, i +(i))
    ~&  [%bad-pair i.a i.b %index i]
    $(a t.a, b t.b, bad [i bad], i +(i))
  --
::
++  test-chunk-merge
  =/  bn  bignum
  =/  p=@  +((div max-target-atom:t 8))
  ::
  =/  num=@  p
  =/  big=@  (merge:bn (chunk:bn p))
  %+  expect-eq  !>(num)
  !>(big)
::
++  test-accumulated-work-genesis
  =/  expect-work=@  (div max-target-atom:t +(genesis-target-atom:t))
  %+  expect-eq  !>(expect-work)
  !>((merge:bignum ~(accumulated-work get:page:t default-genesis-page:h)))
::
++  test-accumulated-work-100-pages
  =/  con=consensus-state  initial-consensus-state:h
  =^  last-page=page:t  con  (add-n-pages:h 99 con default-retain:h)
  ::
  =/  expect-work=@  (mul 100 (div max-target-atom:t +(genesis-target-atom:t)))
  %+  expect-eq  !>(expect-work)
  !>((merge:bignum ~(accumulated-work get:page:t last-page)))
::
++  test-a-pt-conversion
  =/  a-pt-expect=(list a-pt:curve:cheetah)
    :~  default-a-pt-1:h
        default-a-pt-2:h
        default-a-pt-3:h
    ==
  =/  a-pt-actual=(list a-pt:curve:cheetah)
    %+  turn  a-pt-expect
    |=  a=a-pt:curve:cheetah
    ^-  a-pt:curve:cheetah
    (base58-to-a-pt:cheetah (a-pt-to-base58:cheetah a))
  ::
  %+  expect-eq
    !>(a-pt-expect)
  !>(a-pt-actual)
::
++  test-schnorr-pubkey-conversion
  ::  this just calls the same arms as test-a-pt-conversion but we do a separate test anyways to ensure those arms dont break
  =/  pk-expect=(list sig:t)
    :~  p:default-keys-1:h
        p:default-keys-2:h
        p:default-keys-3:h
    ==
  =/  pk-actual=(list sig:t)
    %+  turn  pk-expect
    |=  pk=sig:t
    ^-  sig:t
    (from-b58:sig:t (to-b58:sig:t pk))
  ::
  %+  expect-eq
    !>(pk-expect)
  !>(pk-actual)
::
++  test-coinbase-split-fibonacci
  =/  total=coins:t  999.999.999
  =/  shares=(z-map sig:t @)
    (~(gas z-by *(z-map sig:t @)) ~[[p:default-keys-1:h 21] [p:default-keys-2:h 13]])
  =/  split=coinbase-split:v0:t
    (new:coinbase-split:v0:t total shares)
  =/  sum=coins:t
    %+  roll  ~(val z-by split)
    |=  [c=coins:t sum=coins:t]
    (add c sum)
  %+  expect-eq
    !>  :*  total
            617.647.058
            382.352.941
        ==
  !>  :*  sum
          (~(got z-by split) p:default-keys-1:h)
          (~(got z-by split) p:default-keys-2:h)
      ==
::
++  test-block-id-b58-conversion
  ::  test block-id conversion to/from base58 along with to-list and list-to-tuple conversion
  =/  bid-string=@t  'DfPNrKYEzZgnxBAgiSeqz3D8dKYKTtyQ8z98TRKH94Bhv49qhHdHpKy'
  =/  bid=block-id:t  (from-b58:block-id:t bid-string)
  =/  bid-list=(list @)  (to-list:block-id:t bid)
  =/  bid-tuple  (list-to-tuple:tip5 bid-list)
  =/  bid2=block-id:t  (need ((soft block-id:t) bid-tuple))
  =/  bid-string2=@t  (to-b58:block-id:t bid2)
  %+  expect-eq
    !>([bid bid-string])
  !>([bid2 bid-string2])
--
