::  tests for the slip10 lib
::
::  Test vectors generated by python script, using code validated
::  on secp256k1 test vectors
::
/=  *  /common/test
/=  slip10  /common/slip10
/=  z  /common/zeke
=,  curve:cheetah:z
=,  slip10
::
|%
::  .mk: master key
::  .dp: derivation path
::  .id: identifier
::  .sk: secret key
::  .pk: public key
::  .cc: chaincode
+$  vector  [mk=byts dp=tape id=@ux sk=@ux pk=@ux cc=@ux]
::
++  test-slip10-derive-public
  ^-  tang
  =/  vec=vector
    :*  [64 0xfffc.f9f6.f3f0.edea.e7e4.e1de.dbd8.d5d2.cfcc.c9c6.c3c0.bdba.b7b4.b1ae.aba8.a5a2.9f9c.9996.9390.8d8a.8784.817e.7b78.7572.6f6c.6966.6360.5d5a.5754.514e.4b48.4542]
        "m/2147483645"
        0xe927.ffcd.eb1f.8bef.f41c.07ec.e7c9.a9fa.eb70.b75f
        0x600d.2773.9770.b54a.a1ab.ac35.26ae.8918.1787.b547.0472.5025.1885.4e17.c268.e04b
        0x1.8fa0.b44a.db6c.f593.e2aa.307b.9990.da12.06c9.3c21.fb71.73cc.f2b2.ed96.b7fc.e2a1.ce04.a679.512a.5faa.ce6b.8e4f.1abc.17e0.c100.d6c3.b849.0be9.b48f.4cac.d90e.7dfc.70e0.1d0e.0aad.3936.a215.3908.dd03.2630.9bfa.8d81.06ce.72f2.9266.26f8.6670.35b8
        0x4483.f44c.05fe.cc39.ff4a.707c.b125.bd60.bfba.c8a3.4cf9.c2e2.fb31.5251.c822.68bf
    ==
  ;:  weld
    %+  category  "identity"
    %+  expect-eq
      !>  id.vec
      !>  `@ux`identity:(derive-public:(from-seed mk.vec current-protocol) 2.147.483.645)
  ::
    %+  category  "public-key"
    %+  expect-eq
      !>  pk.vec
    !>  `@ux`public-key:(derive-public:(from-seed mk.vec current-protocol) 2.147.483.645)
  ::
    %+  category  "chaincode"
    %+  expect-eq
      !>  cc.vec
      !>  `@ux`chain-code:(derive-public:(from-seed mk.vec current-protocol) 2.147.483.645)
  ==
::
++  test-slip10-derive-private
  ^-  tang
  |^  ;:  weld
        %+  category  "identity"
        (zing (turn vectors check-id))
        %+  category  "public-key"
        (zing (turn vectors check-pk))
        %+  category  "private-key"
        (zing (turn vectors check-sk))
        %+  category  "chaincode"
        (zing (turn vectors check-cc))
      ==
  ::
  ++  check-id
    |=  vector
    %+  expect-eq
      !>  id
      !>  `@ux`identity:(derive-path:(from-seed mk current-protocol) dp)
  ::
  ++  check-pk
    |=  vector
    %+  expect-eq
      !>  pk
      !>  `@ux`public-key:(derive-path:(from-seed mk current-protocol) dp)
  ::
  ++  check-sk
    |=  vector
    %+  expect-eq
      !>  sk
      !>  `@ux`private-key:(derive-path:(from-seed mk current-protocol) dp)
  ::
  ++  check-cc
    |=  vector
    %+  expect-eq
      !>  cc
      !>  `@ux`chain-code:(derive-path:(from-seed mk current-protocol) dp)
  ::
  ++  vectors
    ^-  (list vector)
    :~  :*  [16 0x1.0203.0405.0607.0809.0a0b.0c0d.0e0f]
            "m/0'"
            0x4dd0.a800.ce4b.2920.d32e.7939.2dee.b10e.627c.d657
            0x75ac.9f30.07d7.f862.8cad.0309.a54c.4ed6.81f3.4a9f.1734.b1e7.3657.75d4.5fb1.00fb
            0x1.5c32.c028.b1f2.3451.bb53.0ac4.cb2a.b161.2ef4.4383.6ed3.3331.b310.a82d.574a.3371.950d.29b7.1294.19a0.203c.f3d5.8a05.306f.4206.ab91.89ac.6950.787c.babb.c2da.05b4.18d6.be66.3a8c.5aa6.9d63.7e9b.29e3.fee8.8cf4.9902.2bb0.0c52.0108.d41f.11a7.4436
            0x4f3e.ed47.cd91.bd3c.6c6b.8fd6.87cb.b54c.5892.af99.76b2.56f2.b801.2d5b.bcf2.737e
        ==
        :*  [16 0x1.0203.0405.0607.0809.0a0b.0c0d.0e0f]
            "m/0'/1"
            0xdab6.74a8.52af.1ebf.b5ab.2a94.ee86.8a76.7ad0.2f4d
            0x1276.178a.65a3.8452.d065.6738.e706.85aa.0b0a.4bf4.df4e.cc0d.1a45.d04a.8007.8f93
            0x1.d6ea.5413.2918.8e59.991c.a087.6492.384b.09b0.42e3.83b8.ceb7.175a.2a16.bc4c.89e5.8392.1944.cfbe.6107.b3a4.07c7.6e6e.3764.a866.5452.5aeb.11be.eb11.5d5e.e005.f593.7dc8.a188.b932.6d90.e5b7.82c4.b135.0dd6.0614.cba0.863b.c954.9773.b6a7.5b09.f0db
            0x57d.db66.4726.4334.975c.2754.cbbb.2ccf.319f.b14b.e55b.4353.580f.bc98.17fd.682b
        ==
        :*  [16 0x1.0203.0405.0607.0809.0a0b.0c0d.0e0f]
            "m/0'/1/2'"
            0xfb8e.19c7.0dd0.5fa8.9d3b.2c5f.8b6e.4a69.b67b.eaab
            0x6df8.3157.681e.1955.5c5a.7a55.19d5.21a3.ffa6.697b.c3f9.0c2b.e11c.8c7b.d3f9.e195
            0x1.0966.544a.022a.9372.c555.4807.78d7.346b.3ee1.0aba.dedf.b71e.b153.5c35.e28e.9e2b.575e.9f53.fa9a.389c.7757.59af.6a42.4adb.f520.7218.016f.5cfe.4e51.5acf.e7d4.32ee.d69e.95a3.3983.7e1e.0d0b.db5a.fa6e.abf8.d3b9.2554.c08e.a644.dfba.a119.e8f0.c45f
            0xa52.3430.3dbd.9f35.c19e.8606.f497.7972.46c3.9f56.5055.9908.fa0e.6d60.6dbb.5b55
        ==
        :*  [16 0x1.0203.0405.0607.0809.0a0b.0c0d.0e0f]
            "m/0'/1/2'/2"
            0xd674.bd57.527b.7f67.1e58.16c5.2186.dffd.27a4.db8d
            0x2958.7e74.1f66.3304.1233.7a39.10aa.3f39.4619.4fc9.0293.7f2e.427f.128d.262f.5d0c
            0x1.be06.9524.5d2e.33ac.141c.88bc.8057.9bbf.a3c4.307e.61ff.f0ab.3cfa.4ca3.7aa8.5bc7.ea11.276d.ca65.306c.d15e.53dc.d9d1.4aff.5472.68cc.ecb8.b649.a099.e2f0.361c.661e.2354.476b.5494.bf96.5d6e.734a.b7ef.e11b.4372.1336.d02f.c4dc.4851.276c.e97d.8109
            0x1a1c.2cd1.e691.2edc.9b07.6308.6e9c.9148.8ded.ff10.9c75.4317.1c4a.49fb.023c.f156
        ==
        :*  [16 0x1.0203.0405.0607.0809.0a0b.0c0d.0e0f]
            "m/0'/1/2'/2/1000000000"
            0xb2d3.5c15.59f1.a5bd.31b4.8290.9447.9241.6785.0710
            0x64fa.55bd.c215.1ff7.6122.2dc0.feec.636b.863f.6a33.a9c0.4aa9.4008.85dd.ee14.32ca
            0x1.48fc.b0e9.ee2a.be20.11f1.58c1.06b7.f763.3620.f9e4.a2ce.432a.f3c5.2cc8.62c5.e4f3.6344.7dcb.4dd0.07a3.b077.c17f.1fe5.37fd.48fa.27c3.308d.cf42.e51d.51be.8f48.b035.20b2.87e7.df3e.f8d2.b2a8.0fba.4794.95b9.3a1d.0464.6581.4401.a171.57f6.2d50.bc91
            0xbcf3.88d0.c304.9ec9.7d34.f648.a5a9.db34.a499.617f.0e7e.2538.26d9.9f10.0af7.a015
        ==
        :*  [64 0xfffc.f9f6.f3f0.edea.e7e4.e1de.dbd8.d5d2.cfcc.c9c6.c3c0.bdba.b7b4.b1ae.aba8.a5a2.9f9c.9996.9390.8d8a.8784.817e.7b78.7572.6f6c.6966.6360.5d5a.5754.514e.4b48.4542]
            "m/0"
            0x5889.63ae.dd28.333b.afd2.a664.e9a4.30a0.d8a0.42c1
            0x480d.21a7.9ed2.4927.4ac9.90fd.e814.89fd.594e.eae5.0d42.11b3.fc63.1b30.ff48.3d53
            0x1.a04d.5a8a.fed8.25a1.791b.d05f.1222.ad9e.314c.4471.83f7.d242.6f06.3360.4c0a.dbb9.df86.afd6.d564.fdee.224f.fa05.4f0e.4592.6cb4.985d.54bd.19ac.2e84.4629.083e.1eb0.b89e.9fae.5b49.1547.5f3d.90e3.9a1b.8a49.a75b.7580.d911.6a17.5493.c4e7.38fc.08ef
            0x2e6c.af70.2864.085f.3066.9772.3ef6.4706.015e.fdac.6e3b.e6c4.b8e1.7bc2.f83d.0b19
        ==
        :*  [64 0xfffc.f9f6.f3f0.edea.e7e4.e1de.dbd8.d5d2.cfcc.c9c6.c3c0.bdba.b7b4.b1ae.aba8.a5a2.9f9c.9996.9390.8d8a.8784.817e.7b78.7572.6f6c.6966.6360.5d5a.5754.514e.4b48.4542]
            "m/0/2147483647'"
            0x1227.8fed.7688.0ae9.5a56.a0ff.3c6e.51e0.40c1.5a9e
            0xbc7.1206.4dde.f1df.8d7e.daa7.c6c5.51b9.266e.fb6b.3547.5c6a.96c6.3b86.0ab2.d498
            0x1.434e.3442.5e08.dfa8.7ec1.9a09.0f82.172f.c4dd.f3d3.d830.beda.9272.48d6.7bf1.27ff.f995.537a.1518.b884.3f8a.976c.b8c3.fd98.6923.2ada.6612.d73d.24c0.b02d.0554.e9b9.5413.91d4.1a1a.2b5f.db0a.9cd3.24de.cd25.3fa9.13ac.6163.2305.e7fa.0012.2186.b6ef
            0xd9c.f681.4a5d.7fda.a362.948d.6916.01d4.7c43.afaf.bbff.aad0.d7a2.19d9.2cf0.8cbe
        ==
        :*  [64 0xfffc.f9f6.f3f0.edea.e7e4.e1de.dbd8.d5d2.cfcc.c9c6.c3c0.bdba.b7b4.b1ae.aba8.a5a2.9f9c.9996.9390.8d8a.8784.817e.7b78.7572.6f6c.6966.6360.5d5a.5754.514e.4b48.4542]
            "m/0/2147483647'/1"
            0x936b.a232.4012.612b.ccc7.0323.be47.dfd5.0a0c.21cb
            0x3a88.832d.077b.c83f.4dcf.7bb4.5075.35bd.9099.aeda.3c6a.8619.378f.62d9.d035.4671
            0x1.0e2c.b12e.a5f1.ae12.6c64.fccb.7cf9.1879.ec99.fce0.7ad3.fc35.e0b5.1cdf.380d.954e.c5c3.e32f.75a3.addb.2cd4.99c3.d3eb.b666.20b6.b293.02ba.cda3.a70d.30b6.951f.c808.a9cb.063d.40bd.b179.694b.3c73.fe47.d60b.05fa.0ef0.b832.042c.5386.3b84.2a55.b0a3
            0x53fb.9a9c.8096.b350.53c1.8d92.cdd4.eecf.cbbb.aefc.e359.ea56.2f9f.4902.99ba.732c
        ==
        :*  [64 0xfffc.f9f6.f3f0.edea.e7e4.e1de.dbd8.d5d2.cfcc.c9c6.c3c0.bdba.b7b4.b1ae.aba8.a5a2.9f9c.9996.9390.8d8a.8784.817e.7b78.7572.6f6c.6966.6360.5d5a.5754.514e.4b48.4542]
            "m/0/2147483647'/1/2147483646'"
            0x6b31.58e1.c0ed.dd43.c721.d476.1f5c.d62b.8ba2.83ae
            0x464f.5c4a.d135.4196.a19e.6741.081d.7129.988e.7890.3b8a.8fb4.f92a.28ec.6e3a.2d40
            0x1.5438.d22f.98d5.c1d8.6217.5606.5b1c.24cc.90e3.a210.d0f6.c7ee.4206.2aef.1301.d211.c5d6.4392.7117.e227.0c08.f1be.d8ac.8b06.7e01.defa.c79d.e444.3352.c4cb.5084.20a1.687e.84d7.54cd.b20a.bcf2.dd5c.199c.5aec.8a6f.23d4.b30d.1717.2daf.7ed8.5e5b.6933
            0xda6a.12a7.32c4.dad8.ac1e.15d4.1749.06e1.e6d9.5dab.4230.a16d.ad86.2222.8ff1.0a18
        ==
        :*  [64 0xfffc.f9f6.f3f0.edea.e7e4.e1de.dbd8.d5d2.cfcc.c9c6.c3c0.bdba.b7b4.b1ae.aba8.a5a2.9f9c.9996.9390.8d8a.8784.817e.7b78.7572.6f6c.6966.6360.5d5a.5754.514e.4b48.4542]
            "m/0/2147483647'/1/2147483646'/2"
            0x87f5.5e3d.a228.4e7d.a311.e3e0.60c0.8852.882a.3859
            0x2e33.89ce.2eb4.77e1.7ac6.b094.3c2f.8f0b.bb68.b47a.8089.564d.5234.1f93.2ad9.ce8d
            0x1.f1c1.a461.a1c6.a7b3.3074.fc8b.4de9.b5a8.52f4.3bc7.2364.53f6.1987.3bfb.6def.2c2e.f145.0cc4.fdcd.1516.f169.7fb2.ff1b.d168.1c1f.2fbc.ec76.6361.fac1.fd2d.f987.a213.5287.e775.2609.99de.4467.892c.80f4.6ead.4b95.73c3.953d.302f.951f.dd46.87ae.052a
            0x692.bfc3.fcf8.b713.7b1d.9377.b9e5.176b.3921.b18f.c65e.daaa.5b38.7254.e2a7.fbbd
        ==
        :*  [64 0x4b38.1541.583b.e442.3346.c643.850d.a4b3.20e4.6a87.ae3d.2a4e.6da1.1eba.819c.d4ac.ba45.d239.319a.c14f.863b.8d5a.b5a0.d0c6.4d2e.8a1e.7d14.57df.2e5a.3c51.c732.35be]
            "m/0'"
            0xbcb5.b496.b72e.6be2.ad0c.83af.977c.e342.4d6c.ee86
            0x64f.3bfa.78c9.3ae0.5204.dcd5.ef04.88c2.0e4f.112c.15b7.657c.1193.6a7e.2c10.b74b
            0x1.166a.fde5.d1bc.1efa.69cb.1d31.401e.403b.2b7d.0519.6044.202d.32e1.66ac.6698.15ec.e35b.3892.7aca.b305.8b17.893d.a958.12bc.cc97.33da.7605.e51a.8e02.24d3.951e.69a4.a880.2e01.7b6b.8205.d2e9.9452.a8ad.746c.ab9e.7bb0.9f04.37aa.d81e.9f75.e8fd.8258
            0xe262.6e93.fcb8.ca0f.d602.c2bb.2812.399d.205d.42c5.38a0.f83b.0528.198b.7d96.a4c2
        ==
        :*  [32 0x3ddd.5602.2858.99a9.4611.4506.157c.7997.e544.4528.f300.3f61.3471.2147.db19.b678]
            "m/0'"
            0x4af0.8c0f.80db.51be.c15e.3b56.af9f.897d.d0ee.51aa
            0x641a.1574.b098.2ffd.eb98.e9c0.d03f.63dc.14dc.0316.4ad5.859c.41ef.b0bc.bd72.556e
            0x1.4076.2a08.788c.e0e3.43da.9124.6b59.98ef.4fbe.1939.e1a2.d4dd.8be4.bdf9.de98.a3a0.21af.5756.3a3a.b1ec.acd9.5976.10e1.6e2a.268c.46eb.cc21.69c8.e6bb.9be9.5730.7611.34ec.7d12.8901.2bd8.834b.76ad.2841.4860.eb69.dd25.d9f6.ec2a.355b.3cf5.68d0.2e88
            0xddfb.b84b.a7c0.84b1.845e.29e5.1654.3db6.d4c5.88a1.1770.ccf4.e769.b4ef.2d32.5298
        ==
        :*  [32 0x3ddd.5602.2858.99a9.4611.4506.157c.7997.e544.4528.f300.3f61.3471.2147.db19.b678]
            "m/0'/1'"
            0xaf65.2bbc.6734.0830.1d8b.3669.a5ac.b399.c531.2b1b
            0x741b.4b4f.fe3c.feb8.0f66.218a.0980.e06b.ad6d.6d0b.de90.dc59.c8b5.00b5.4f40.8227
            0x1.872d.b7d4.d9e4.5008.6cff.9915.0ca4.9333.f08e.f968.742e.d626.289b.3215.551f.2bde.b4a8.0686.0f00.c10d.dd41.e70c.5d12.8ae6.5dcd.62f4.7ff9.4fd0.2b1e.d978.95b8.e788.9cb0.6bd8.d575.78e1.f968.0a51.467a.ce59.04e0.b353.a5e1.97da.173d.78d7.1ed4.d471
            0x44bf.2414.7d0e.c853.386e.3f02.3074.1d88.e2b4.45f7.e5c9.b1d6.8882.0bcd.e12e.6f95
        ==
    ==
  --
--
