[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  flush_jitter = "1s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true

[[inputs.statsd]]
  protocol = "udp"
  service_address = ":8125"
  parse_data_dog_tags = true
  datadog_extensions = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
