[package]
name = "nockchain-bridge-sequencer"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[features]
default = []
jemalloc = []
tracing-heap = ["tracy-client"]

[dependencies]
bridge = { path = "../bridge" }
clap.workspace = true
nockapp.workspace = true
nockchain.workspace = true
nockvm.workspace = true
tikv-jemallocator.workspace = true
tokio.workspace = true
tracing.workspace = true
tracy-client = { workspace = true, optional = true }

[lints]
workspace = true
